#CIRCUIT BREAKER
resilience4j.circuitbreaker:
  instances:
    product:
      allowHealthIndicatorToFail: false
      registerHealthIndicator: true
      slidingWindowType: COUNT_BASED
      slidingWindowSize: 5
      failureRateThreshold: 50
      waitDurationInOpenState: 15000 # 15 seconds
      permittedNumberOfCallsInHalfOpenState: 3
      automaticTransitionFromOpenToHalfOpenEnabled: true
      ignoreExceptions:
        - com.codeburps.exception.InvalidRequestException
      
#SWAGGER
springdoc:
  swagger-ui:
    path: /swagger-ui.html

# CATALOG SERVICE ROOT
api:
  catalog:
    baseurl: http://localhost:8081

#ACTUATOR
management:
  endpoints:
    web:
      exposure:
        include: "*"
    health:
      show-details: always

  health.circuitbreakers.enabled: true




